version: "4.16.2"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=my_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "4200:5000"
    environment:
      - UPLOAD_PATH=/files
      - UPLOADED_PATH=/home/app/files
    volumes:
      - ./uploads:/home/app/files
volumes:
  postgres:
